version: "3.8"

services:
  webserver:
    image: nginx:latest
    container_name: webserver
    ports:
      - "8080:80"
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d
    links:
      - php
    networks:
      - laravel-network
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.1-fpm
    container_name: php_docker
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: php
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - laravel-network
networks:
  laravel-network:
    driver: bridge