version: "3.9"

services:
  uto:
    image: nginx:latest
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - uto-network
    links:
      - utophp
  utophp:
    image: php:8.1-fpm
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - uto-network
networks:
  uto-network:
    driver: bridge